In [1]:
# Load Pandas and Numpy

import pandas as pd
import numpy as np

# Read CSV file 

df = pd.read_csv('mtcars.csv')

In [2]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2


In [3]:
# Sample Size
n = df.shape[0]
n

32

In [4]:
# Target variable is mpg. We define it as matrix of order nX1.

y = np.transpose(np.asmatrix(df['mpg']))
y[:]

matrix([[21. ],
        [21. ],
        [22.8],
        [21.4],
        [18.7],
        [18.1],
        [14.3],
        [24.4],
        [22.8],
        [19.2],
        [17.8],
        [16.4],
        [17.3],
        [15.2],
        [10.4],
        [10.4],
        [14.7],
        [32.4],
        [30.4],
        [33.9],
        [21.5],
        [15.5],
        [15.2],
        [13.3],
        [19.2],
        [27.3],
        [26. ],
        [30.4],
        [15.8],
        [19.7],
        [15. ],
        [21.4]])

In [5]:
# First we define the intercept of the model
Intercept = pd.DataFrame(np.ones(n))
Intercept

,0
0,1.0
1,1.0
2,1.0
3,1.0
4,1.0
5,1.0
6,1.0
7,1.0
8,1.0
9,1.0


In [6]:
# We consider 3 variables as predictor i.e. hp, weight and displacement as predictor for mpg
Xdf = df[['hp','wt','disp']]

# Add intercept to Xdf
Xdf = pd.concat([Intercept,Xdf],axis=1)
Xdf.head()

,0,hp,wt,disp
0,1.0,110,2.620,160.0
1,1.0,110,2.875,160.0
2,1.0,93,2.320,108.0
3,1.0,110,3.215,258.0
4,1.0,175,3.440,360.0


The design matrix X is defined as matrix x from Xdf which is of the datatype dataframe.

In [7]:
X =  np.asmatrix(Xdf)
X[:,:]

matrix([[  1.   , 110.   ,   2.62 , 160.   ],
        [  1.   , 110.   ,   2.875, 160.   ],
        [  1.   ,  93.   ,   2.32 , 108.   ],
        [  1.   , 110.   ,   3.215, 258.   ],
        [  1.   , 175.   ,   3.44 , 360.   ],
        [  1.   , 105.   ,   3.46 , 225.   ],
        [  1.   , 245.   ,   3.57 , 360.   ],
        [  1.   ,  62.   ,   3.19 , 146.7  ],
        [  1.   ,  95.   ,   3.15 , 140.8  ],
        [  1.   , 123.   ,   3.44 , 167.6  ],
        [  1.   , 123.   ,   3.44 , 167.6  ],
        [  1.   , 180.   ,   4.07 , 275.8  ],
        [  1.   , 180.   ,   3.73 , 275.8  ],
        [  1.   , 180.   ,   3.78 , 275.8  ],
        [  1.   , 205.   ,   5.25 , 472.   ],
        [  1.   , 215.   ,   5.424, 460.   ],
        [  1.   , 230.   ,   5.345, 440.   ],
        [  1.   ,  66.   ,   2.2  ,  78.7  ],
        [  1.   ,  52.   ,   1.615,  75.7  ],
        [  1.   ,  65.   ,   1.835,  71.1  ],
        [  1.   ,  97.   ,   2.465, 120.1  ],
        [  1.   , 150.   ,   3.52 

In [8]:
Xt = np.transpose(X)

Calculate X'X

In [9]:
Xt*X

matrix([[3.20000000e+01, 4.69400000e+03, 1.02952000e+02, 7.38310000e+03],
        [4.69400000e+03, 8.34278000e+05, 1.64717440e+04, 1.29136440e+06],
        [1.02952000e+02, 1.64717440e+04, 3.60901070e+02, 2.70914888e+04],
        [7.38310000e+03, 1.29136440e+06, 2.70914888e+04, 2.17962747e+06]])

Calculate inverse of X'X

In [10]:
XtX_inv = np.linalg.inv(Xt*X)
XtX_inv

matrix([[ 6.39800586e-01, -1.29284038e-03, -2.73552559e-01,
          1.99885645e-03],
        [-1.29284038e-03,  1.87791901e-05,  2.71270749e-04,
         -1.01185806e-05],
        [-2.73552559e-01,  2.71270749e-04,  1.63235239e-01,
         -1.26302737e-03],
        [ 1.99885645e-03, -1.01185806e-05, -1.26302737e-03,
          1.53816695e-05]])

Now calculating regressor beta cap = (X'X)^-1.X'y

In [11]:
beta_hat = XtX_inv*Xt*y
beta_hat

matrix([[ 3.71055053e+01],
        [-3.11565508e-02],
        [-3.80089058e+00],
        [-9.37009081e-04]])

In [12]:
np.round(beta_hat,4)

array([[ 3.71055e+01],
       [-3.12000e-02],
       [-3.80090e+00],
       [-9.00000e-04]])

Now we will implement ordinary least square using statsmodel

In [13]:
import statsmodels.api as sm

In [14]:
#fit linear regression model
model = sm.OLS(y,X).fit()

#view model summary
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.827
Model:                            OLS   Adj. R-squared:                  0.808
Method:                 Least Squares   F-statistic:                     44.57
Date:                Fri, 30 Jan 2026   Prob (F-statistic):           8.65e-11
Time:                        11:16:43   Log-Likelihood:                -74.321
No. Observations:                  32   AIC:                             156.6
Df Residuals:                      28   BIC:                             162.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         37.1055      2.111     17.579      0.0

In [27]:
from sklearn.linear_model import LinearRegression

X = np.asarray(X)
y = np.asarray(y)

model = LinearRegression(fit_intercept = False)
model.fit(X,y)

LinearRegression(fit_intercept=False)

In [28]:
beta = model.coef_
alpha = model.intercept_

In [29]:
print(beta)
print(alpha)

[[ 3.71055053e+01 -3.11565508e-02 -3.80089058e+00 -9.37009081e-04]]
0.0
